database:
  host: localhost
  port: 5432
  username: dart
  password: dart
  databaseName: dart_test
translationEngines:
- type: baidu
    name: Baidu
    identifier: 
    option:
      appId: 
      appKey: 
  - type: caiyun
    name: Caiyun
    identifier: 
    option:
      token: 
      requestId: 
  - type: cloudoptai
    name: CloudoptAI
    identifier: 
  - type: deepl
    name: DeepL
    identifier: 
    option:
      authKey: 
  - type: ibmwatson
    name: IBMWatson
    identifier: 
    option:
      apiKey: 
      apiUrl: 
  - type: iciba
    name: Iciba
    identifier: 
    option:
      key: 
  - type: sogou
    name: Sogou
    identifier: 
    option:
      pid: 
      key: 
  - type: tencent
    name: Tencent
    identifier: 
    option:
      secretId: 
      secretKey: 
  - type: youdao
    name: Youdao
    identifier: 
    option:
      appKey: 
      appSecret: 
