name: translate_openapi
description: An translate open api.
version: 0.0.1
author: LiJianying <lijy91@foxmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  jaguar: any
  jaguar_reflect: any
  yaml: ^2.2.1

  translate_client:
    path: ./dart_pkgs/packages/translate_client
  translation_engine_baidu:
    path: ./dart_pkgs/packages/translation_engine_baidu
  translation_engine_caiyun:
    path: ./dart_pkgs/packages/translation_engine_caiyun
  translation_engine_cloudoptai:
    path: ./dart_pkgs/packages/translation_engine_cloudoptai
  translation_engine_deepl:
    path: ./dart_pkgs/packages/translation_engine_deepl
  translation_engine_ibmwatson:
    path: ./dart_pkgs/packages/translation_engine_ibmwatson
  translation_engine_iciba:
    path: ./dart_pkgs/packages/translation_engine_iciba
  translation_engine_sogou:
    path: ./dart_pkgs/packages/translation_engine_sogou
  translation_engine_tencent:
    path: ./dart_pkgs/packages/translation_engine_tencent
  translation_engine_youdao:
    path: ./dart_pkgs/packages/translation_engine_youdao

dev_dependencies:
  build_runner:
  jaguar_generator:

# dependency_overrides:
#   translate_client:
#     path: ../dart_pkgs/packages/translate_client
#   translation_engine_baidu:
#     path: ../dart_pkgs/packages/translation_engine_baidu
#   translation_engine_caiyun:
#     path: ../dart_pkgs/packages/translation_engine_caiyun
#   translation_engine_cloudoptai:
#     path: ../dart_pkgs/packages/translation_engine_cloudoptai
#   translation_engine_deepl:
#     path: ../dart_pkgs/packages/translation_engine_deepl
#   translation_engine_ibmwatson:
#     path: ../dart_pkgs/packages/translation_engine_ibmwatson
#   translation_engine_iciba:
#     path: ../dart_pkgs/packages/translation_engine_iciba
#   translation_engine_sogou:
#     path: ../dart_pkgs/packages/translation_engine_sogou
#   translation_engine_tencent:
#     path: ../dart_pkgs/packages/translation_engine_tencent
#   translation_engine_youdao:
#     path: ../dart_pkgs/packages/translation_engine_youdao
